### ISSUE TITLE
Background and icon colors fliped

### ISSUE THREAD

**Issue by pchabros** [abdelhakimrafik/icon2font#5]
Hi, I'm trying to export the following icons:

![image](https://user-images.githubusercontent.com/24566904/224033605-1c732758-3a79-45c2-8308-d8f9616161f2.png)

And some icons are white with black background:

![image](https://user-images.githubusercontent.com/24566904/224033786-b15efb34-cdce-4189-8243-946efc905dc5.png)

Am I doing something wrong?

Also, when I try to export dark icons one by one they look good:

![image](https://user-images.githubusercontent.com/24566904/224036225-5a9723c0-ce33-45ee-aa3d-382581cb11f5.png)

**Comment by abdelhakimrafik** [comment]
### Issue:
Icons created with strokes cannot be converted to font icons.

### Solution:
Convert icons to use `fill` instead of `stroke`.

### Steps to Resolve:
Select the stroke elements of the icons and use the key combination (Ctrl+Shift+O) or (Cmd+Shift+O) for `Outline Stroke`.
